# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 734969488f1a72f14f9e063146e1f10fb7b78c1671b6e06c925b053b5532373850936bb85a6c706712a4150c8e3c3d432197159aeab07662df948ff63efa1feb

test:
  secret_key_base: 1366744931ebdeef050616323fb36e7c430506aff40efb69dc0f928041702f27352e0497a245b7e65c5199c6827523638ee72989d302c20f095e636c459d5f62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
